version: '3'
services:
  spigot:
    build: images/alpine
    environment:
    - REV=latest
    - POLL=true
    - EULA=TRUE
    - OPS=MousePak
    - PVP=false
    - WORLDBORDER=false
    - DYNMAP=false
    - CLEARLAG=false
    - ESSENTIALS=true
    - ESSENTIALSPROTECT=true
    - ESSENTIALSCHAT=true
    - PERMISSIONS=true
    volumes:
    - ./data:/minecraft
    ports:
    - "25565:25565"
#    - "8123:8123"
